image: electronuserland/builder:wine

cache:
  paths:
  - node_modules/
  - app/node_modules/

variables:
  DEBUG_PROD: 'true'

before_script:
- yarn install

stages:
- lint
- test
- build
- e2e
- package

lint:
  stage: lint
  script:
  - npm run lint

unit_test:
  stage: test
  script:
  - npm run test

build:
  stage: build
  script:
  - npm run build
  artifacts:
    paths:
    - app/dist/
    - app/app.html
    - app/main.prod.js
    - app/main.prod.js.map
    - app/package.json

package_linux_and_windows:
  stage: package
  script:
  - npm run package-linux-windows-ci
  only:
  - master
  artifacts:
    paths:
    - release/*.deb
    - release/*.exe
